baseurl = "https://www.andrewsalko.space"
title = "Developer's blog"
author = "Andrew Salko"
canonifyurls = true
paginate = 3
theme = "aether"

enableRobotsTXT= true

languageCode = "en-US"

googleAnalytics="UA-93731751-2"

[params]
    brand = "Developer's blog"
    description = ".NET developer blog"
    bgimg = "img/natural_paper.png"

[markup]
  [markup.highlight]
    style = "igor"